name: swa-family-flow Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*'
      - '*.json'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10' # set this to the python version to use (supports 3.6, 3.7, 3.8)
      
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r api/requirements.txt -t api/.

      - name: Zip test
        run: zip release.zip ./api/* -r

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_BEACH_0CBA6780F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "/api/" # Api source code path - optional
          output_location: "/dist/family-flow/browser" # Built app content directory - optional
          remote_build: true
          ###### End of Repository/Build Configurations ######
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: true
          ENABLE_ORYX_BUILD: true
  